# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df3d6f1ac07ea368d369365618ab343bd11a407e223d0db82b6b9e90335445acc7ce3cc5a193621cc4f1316d6bd72df1b32d9371c3d65862e0e14bf9333f9959

test:
  secret_key_base: 35c497f9ec3737dfe8047b2fe7d5af86f883a3e07a1f983fdcdac67348b89317f757d8dd88ae7dacbda15e4911158c12f844cad14c52d58b926ae8701c3cb726

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
